import { Router, type IRouter } from 'express';
import authRoutes from './auth.routes.js';
import categoryRoutes from './category.routes.js';
import habitRoutes from './habit.routes.js';
import taskRoutes from './task.routes.js';
import eventRoutes from './event.routes.js';
import syncRoutes from './sync.routes.js';
import accountRoutes from './account.routes.js';
import transactionRoutes from './transaction.routes.js';
import financeRoutes from './finance.routes.js';
import recurringExpenseRoutes from './recurringExpense.routes.js';
import monthlyExpenseRoutes from './monthlyExpense.routes.js';
import adminRoutes from './admin.routes.js';
import pushRoutes from './push.routes.js';
import exerciseRoutes from './exercise.routes.js';
import routineRoutes from './routine.routes.js';
import workoutRoutes from './workout.routes.js';
import statsRoutes from './stats.routes.js';
import resourceRoutes from './resource.routes.js';
import calendarConnectionRoutes from './calendarConnection.routes.js';
import budgetRoutes from './budget.routes.js';
import goalRoutes from './goal.routes.js';
import savingsGoalRoutes from './savings-goal.routes.js';
import weeklyReviewRoutes from './weeklyReview.routes.js';
import analyticsRoutes from './analytics.routes.js';
import timelineRoutes from './timeline.routes.js';
import lifeDebtRoutes from './lifeDebt.routes.js';
import insightRoutes from './insight.routes.js';
import foodRoutes from './food.routes.js';
import recipeRoutes from './recipe.routes.js';
import mealPlanRoutes from './mealPlan.routes.js';
import nutritionLogRoutes from './nutritionLog.routes.js';
import shoppingListRoutes from './shoppingList.routes.js';
import habitMomentRoutes from './habitMoment.routes.js';

const router: IRouter = Router();

router.use('/auth', authRoutes);
router.use('/categories', categoryRoutes);
router.use('/habits', habitRoutes);
router.use('/tasks', taskRoutes);
router.use('/events', eventRoutes);
router.use('/sync', syncRoutes);
router.use('/accounts', accountRoutes);
router.use('/transactions', transactionRoutes);
router.use('/finance', financeRoutes);
router.use('/recurring-expenses', recurringExpenseRoutes);
router.use('/monthly-expenses', monthlyExpenseRoutes);
router.use('/admin', adminRoutes);
router.use('/push', pushRoutes);
router.use('/exercises', exerciseRoutes);
router.use('/routines', routineRoutes);
router.use('/workouts', workoutRoutes);
router.use('/stats', statsRoutes);
router.use('/resources', resourceRoutes);
router.use('/calendar-connections', calendarConnectionRoutes);
router.use('/budgets', budgetRoutes);
router.use('/goals', goalRoutes);
router.use('/savings-goals', savingsGoalRoutes);
router.use('/weekly-reviews', weeklyReviewRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/timeline', timelineRoutes);
router.use('/life-debt', lifeDebtRoutes);
router.use('/insights', insightRoutes);
router.use('/foods', foodRoutes);
router.use('/recipes', recipeRoutes);
router.use('/meal-plans', mealPlanRoutes);
router.use('/nutrition-logs', nutritionLogRoutes);
router.use('/shopping-lists', shoppingListRoutes);
router.use('/habit-moments', habitMomentRoutes);

// Health check
router.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

export default router;
