module.exports = {
  createAccountLocal: jest.fn(),
  updateAccountLocal: jest.fn(),
  deactivateAccountLocal: jest.fn(),
  createTransactionLocal: jest.fn(),
  updateTransactionLocal: jest.fn(),
  deleteTransactionLocal: jest.fn(),
  createTransferLocal: jest.fn(),
  payMonthlyExpenseLocal: jest.fn(),
  undoMonthlyExpensePaymentLocal: jest.fn(),
  createRecurringExpenseLocal: jest.fn(),
  updateRecurringExpenseLocal: jest.fn(),
  deleteRecurringExpenseLocal: jest.fn(),
  createBudgetLocal: jest.fn(),
  updateBudgetLocal: jest.fn(),
  deleteBudgetLocal: jest.fn(),
  createSavingsGoalLocal: jest.fn(),
  updateSavingsGoalLocal: jest.fn(),
  deleteSavingsGoalLocal: jest.fn(),
};
