module.exports = {
  createFoodLocal: jest.fn(),
  updateFoodLocal: jest.fn(),
  deleteFoodLocal: jest.fn(),
  createRecipeLocal: jest.fn(),
  updateRecipeLocal: jest.fn(),
  deleteRecipeLocal: jest.fn(),
  addIngredientLocal: jest.fn(),
  removeIngredientLocal: jest.fn(),
  addLogItemLocal: jest.fn(),
  removeLogItemLocal: jest.fn(),
  createMealPlanLocal: jest.fn(),
  deleteMealPlanLocal: jest.fn(),
  addMealEntryLocal: jest.fn(),
  removeMealEntryLocal: jest.fn(),
  generateShoppingListLocal: jest.fn(),
  syncShoppingListLocal: jest.fn(),
  createShoppingListLocal: jest.fn(),
  deleteShoppingListLocal: jest.fn(),
  checkShoppingItemLocal: jest.fn(),
  linkTransactionLocal: jest.fn(),
};
